---
platform: linux

image_resource:
  type: docker-image
  source: {repository: ubuntu}

inputs:
  - name: web-content
  - name: docker-compose-deployment
  - name: ci-code
outputs:
  - name: update-git

run:
  path: ci-code/update_docker.sh